### ISSUE TITLE
Add `useHotKeys` hook

### ISSUE THREAD

**Issue by anmol-kumar0815** [bigbinary/neeto-hotkeys#3] opened 2023-11-13 09:12 UTC
Part of https://github.com/bigbinary/neeto-commons-frontend/issues/984

@anmol-kumar0815 _A

**Comment by sumanranjanpanda** [comment] 2023-11-30 06:56
@Amaljith-K _a The issue is in the "in progress" column but is not assigned to anyone.

**Comment by Amaljith-K** [comment] 2023-11-30 15:45
@deepakjosp _a please take care of this

**Closed as completed** 2023-12-05 12:41 UTC
Labels: PR, working
